# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :increase_version do
    increment_version_name(app_project_dir: '**/app', bump_type: 'patch')
    increment_version_code(app_project_dir: '**/app')
    current_version
  end

  lane :current_version do 
    version = get_version_name(app_project_dir: '**/app')
    version_code = get_version_code(app_project_dir: '**/app')
    UI.message("Version: " + version + ":"+ version_code)
  end

  desc "Build Debug to Firebase"
  lane :firebase do
    gradle(
      task: "clean assembleDebug",
      project_dir: './android'
    )

    firebase_app_distribution(
      app: "1:729759911657:android:afad31d912b4aa4ac46a78",
      groups: "Internal"
    )
    current_version
  end

  lane :debug_diawi do
    gradle(
      task: "clean assembleDebug",
      project_dir: './android'
    )

    # diawi(
    #   token: ""
    # )

    version = get_version_name(app_project_dir: '**/app')
    version_code = get_version_code(app_project_dir: '**/app')
    UI.message("Android: " + version + "-"+ version_code + " : " + lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI])
  end
end

platform :ios do
  lane :increase_version do
    appName = 'App'

    increment_build_number(
      xcodeproj: './ios/App/' + appName + '.xcodeproj'
    )

    increment_version_number(
      xcodeproj: './ios/App/' + appName + '.xcodeproj',
      bump_type: "patch" # Automatically increment patch version number
    )
  end

  lane :firebase do
    gym(
      workspace: './ios/App/App.xcworkspace',
      silent: true,
      clean: true,
      export_method: "development",
      export_options: {
        provisioningProfiles: { 
          "com.summa-systems.app-dev" => "Summa System Dev - Dev",
        }
      } 
    )

    # firebase_app_distribution(
    #   app: "1:900742591808:ios:5e08b6257cd6d13d50b6a5",
    #   groups: "Manifera"
    # )
  end

  lane :debug_diawi do
    gym(
      workspace: './ios/App/App.xcworkspace',
      silent: true,
      clean: true,
      export_method: "development",
      export_options: {
        provisioningProfiles: { 
          "com.summa-systems.app-dev" => "Summa System Dev - Dev",
        },
        signingCertificate: "iPhone Developer"
      } 
    )

    diawi(
      token: "cdGJFM8DSUksRjGLcdtxqvvHg2RuL2FLZT4TjdJsVT"
    )

    version = get_version_name(app_project_dir: '**/app')
    version_code = get_version_code(app_project_dir: '**/app')
    UI.message("iOS: " + version + "-"+ version_code + " : " + lane_context[SharedValues::UPLOADED_FILE_LINK_TO_DIAWI])
  end

  lane :upload_testflight do
    gym(
      workspace: './ios/App/App.xcworkspace',
      silent: true,
      clean: true,
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
